name: is_gps_open
description: Check if the device GPS is turned on
version: 0.0.1
homepage: https://github.com/Wing-Li/flutter_is_gps_open

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.wingli.is_gps_open
        pluginClass: IsGpsOpenPlugin
      ios:
        pluginClass: IsGpsOpenPlugin
